### ISSUE TITLE
feature request, show the webpack script

### ISSUE THREAD

**Issue by MichaelDimmitt** [Afer1991/to-do-list#1]
1. Add to package.json 
2. Add to readme.md

Lets have the discussion below first. Tell me the webpack command you use on the terminal to build the project.

**Comment by MichaelDimmitt** [comment]
`npm run test` for example would run the test script in the package.json.

**Comment by adrianferreroasensio** [comment]
The terminal command used to build the project is `npx webpack`

**Comment by MichaelDimmitt** [comment]
Please add that script to the readme and package.json
So that when future developers look at your project they can immediately get it working.

**Comment by adrianferreroasensio** [comment]
Script added to both readme and package.json files.

**Comment by MichaelDimmitt** [comment]
cool!
